#!/usr/bin/env python3
"""Validate and optionally import a PromptPoseFX effect.

Usage:
    python scripts/verify_effect.py path/to/code.js --frames 240
    python scripts/verify_effect.py path/to/code.js --save --name "My Effect"
"""

import argparse
import os
import sys
import uuid
from pathlib import Path


BACKEND_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, BACKEND_DIR)

from agent.hard_validate import hard_validate_effect


def main() -> None:
    """Adapt command-line arguments to the shared hard-validation module."""
    parser = argparse.ArgumentParser(description="Validate and import a PromptPoseFX effect")
    parser.add_argument("code", help="Path to the code.js file")
    parser.add_argument("--video-id", default="001", help="Pose-data video ID; default: 001")
    parser.add_argument(
        "--pose-data",
        default="",
        help="Optional path to a Pose JSON timeline; overrides --video-id",
    )
    parser.add_argument("--frames", type=int, default=240, help="Frames to simulate; default: 240")
    parser.add_argument(
        "--timeout-seconds",
        type=float,
        default=10.0,
        help="Maximum simulated-render duration; default: 10",
    )
    parser.add_argument("--save", action="store_true", help="Save valid code to chat_data for preview")
    parser.add_argument("--name", default="", help="Effect name required with --save")
    parser.add_argument("--effect-id", default="", help="Effect ID; generated by default")
    args = parser.parse_args()

    code_path = Path(args.code)
    code = code_path.read_text(encoding="utf-8")
    pose_path = (
        Path(args.pose_data)
        if args.pose_data
        else Path(BACKEND_DIR) / "data" / args.video_id / "smoothed_landmark.json"
    )

    print("== 1/2 Static validation + Simulated rendering ==")
    result = hard_validate_effect(
        code,
        pose_path,
        frames=args.frames,
        timeout_seconds=args.timeout_seconds,
    )
    if not result.passed:
        for error in result.errors:
            print(f"  ❌ {error}")
        sys.exit(1)

    summary = result.render_summary
    assert summary is not None
    counts = summary.draw_calls
    print(
        f"  ✅ {summary.frames} frames completed; draw calls: {summary.total_draw_calls} "
        f"(line={counts.get('line', 0)}, ellipse={counts.get('ellipse', 0)}, "
        f"arc={counts.get('arc', 0)}, rect={counts.get('rect', 0)})"
    )

    print("== 2/2 Preview import ==")
    if not args.save:
        print('  - Not saved; add --save --name "Effect Name" to import for preview')
        return
    if not args.name:
        print("  ❌ --name is required with --save")
        sys.exit(1)

    from chat_manager import ChatManager

    effect_id = args.effect_id or f"verify-{uuid.uuid4().hex[:8]}"
    manager = ChatManager()
    manager.save_effect(effect_id, code, result.params, args.name, status="active")
    manager.save_conversation(effect_id, [
        {"role": "user", "content": f"Imported for preview with verify_effect.py: {args.name}"},
        {"role": "assistant", "content": "The effect is ready to preview in the frontend."},
    ])
    print(f"  ✅ Saved: {effect_id}. Refresh the frontend and select a video to view {args.name}.")


if __name__ == "__main__":
    main()
